# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
#- task: WhiteSource@21
#  inputs:
#    cwd: '$(System.DefaultWorkingDirectory)'
#    projectName: $(Build.Repository.Name)

- task: CmdLine@2

  inputs:
    script: |
      curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      echo "Unified Agent downloaded successfully"
      java -jar /home/vsts/work/whitesource_agent/wss-unified-agent.jar -c /home/vsts/work/1/s/eframe-core/packages/ui/fragment-library/AZDO_wss-unified-agent.config -d /home/vsts/work/1/s/eframe-core/packages/ui/fragment-library -apiKey fd3098875c024122b55b21c4f2caebdaa2da13896b5541fda9efbbf856b67581 -userKey b478bfc860e94ecbb0857e28e7383dde0d8fa9edc71f41ae811303fd6126d7a9 -wss_url https://saas.whitesourcesoftware.com/agent